### PR TITLE
New Logo Proposal: Fancy one

### PR DESCRIPTION
**Pull request by kiselev-nikolay**
Hi. I drew a new logo for you. I find it interesting. But I'll ask on reddit, and add a link to the thread here. I think your current logo would be great to update. Especially since you've done so much since 2018. Thank you very much for that, gin-gonic team!

### CODE REVIEW

**Comment by kiselev-nikolay** [comment]
And I will complete it, according to the criticism and suggestions. Hi all! :)

**Comment by kiselev-nikolay** [comment]
Link on reddit post: https://www.reddit.com/r/golang/comments/o3d6h8/new_gingonic_logo_design/

**Comment by LuckeeDev** [comment]
Love this! I like this better than the previous one.

**Comment by danjmillier** [comment]
This is fantastic!!

**Comment by soypat** [comment]
Call me old fashioned, but I'm not a fan of the underlying gopher face design. I'd much rather it stick to the [source](https://commons.wikimedia.org/wiki/File:Go_gopher_model_sheet.jpg). 
PS: I may be wrong, but the outer stroke thickness of the glass is a bit thick, no?

**Comment by kiselev-nikolay** [comment]
> Call me old fashioned, but I'm not a fan of the underlying gopher face design. I'd much rather it stick to the [source](https://commons.wikimedia.org/wiki/File:Go_gopher_model_sheet.jpg).

Hey @soypat, I think many does. But there are also a room for revisions. I tried an original face, but came up with this

> PS: I may be wrong, but the outer stroke thickness of the glass is a bit thick, no?

Yeah, you might be right. I will try to make it thinner. And will see how it will look. Thanks!

**Comment by kiselev-nikolay** [comment]
@soypat, I did on your advice. What do you think? But if I did it wrong, tell me what's wrong. You can always edit yourself in any vector graphics editor. Here is the [source](https://github.com/gin-gonic/logo/blob/19ff3e79827e454783777eb0de11cd051592e35b/color.svg)



What do the everyone think?

**Comment by hi019** [comment]
@kiselev-nikolay Hey, thanks for this! I like the last one the best. Can we see what it looks like with the eyes looking in opposite directions?

**Comment by appleboy** [comment]
@gin-gonic/maintainers It looks so cute.

**Comment by mewforest** [comment]
Your version is the cutest logo I have ever seen 💯

**Comment by kiselev-nikolay** [comment]
@gin-gonic/maintainers any news?

**Comment by thinkerou** [comment]
> @gin-gonic/maintainers any news?

@kiselev-nikolay thanks, it's a nice version, we should wait @javierprovecho review and feedback.

**Comment by thinkerou** [comment]
> @soypat, I did on your advice. What do you think? But if I did it wrong, tell me what's wrong. You can always edit yourself in any vector graphics editor. Here is the [source](https://github.com/gin-gonic/logo/blob/19ff3e79827e454783777eb0de11cd051592e35b/color.svg)
> 
> 
> 
> What do the everyone think?

maybe we should open one new pull request, and split two comment, and anyone can vote, thanks!

**Comment by kiselev-nikolay** [comment]
Timed out.

**Pull request closed without merging**
