### PR TITLE
New Logo Proposal

### PR DESCRIPTION
**Pull request by ahmednooor**
New Logo Proposal

### CODE REVIEW

**Comment by thinkerou** [comment]
@ahmednooor thank your pull request, can you tell us why change? and the pull request need @javierprovecho review and agree.

**Comment by ahmednooor** [comment]
@thinkerou  ummm no specific reason. I was just free and happens to be a designer as well and i saw there were some unchecked check boxes in readme so i thought of giving it a try. it is just a proposal, if you think it can be used as a sticker and a logo then use it, otherwise feel free to disregard it. Also feel free to keep the files if you are not sure.
thanks.

**Comment by appleboy** [comment]
Any preview screenshot like #6

**Comment by ahmednooor** [comment]
> Any preview screenshot like #6

**Comment by thinkerou** [comment]
@ahmednooor thanks! please see #6 and I will close the pull request, thanks again.

**Pull request closed without merging**
